name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
        os:
          - ubuntu-22.04
        arch:
          - x64

    steps:
      # Checkout the code
<<<<<<< HEAD
      - uses: actions/checkout@v4

      # Set up Julia environment
      - uses: julia-actions/setup-julia@v2
=======
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Julia environment
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
>>>>>>> d4d7d0ab4d7100c8169284283778f3267f5f96fa
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache Julia dependencies
<<<<<<< HEAD
      - uses: julia-actions/cache@v2

      # Install ROS 2 Humble
      - name: Set up ROS 2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/rosdep.key | sudo tee /etc/apt/trusted.gpg.d/ros.asc
          sudo apt update
          sudo apt install -y ros-jazzy-desktop
          source /opt/ros/humble/setup.bash
          echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
          source ~/.bashrc

      # Set up ROS dependencies
      - name: Install ROS dependencies
        run: |
          sudo apt install -y python3-colcon-common-extensions
          sudo apt install -y python3-pip
          pip3 install -U setuptools
          pip3 install colcon-common-extensions

      # Run tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
=======
      - name: Cache Julia Dependencies
        uses: julia-actions/cache@v2

      # Set up ROS 2 
      - name: Set up ROS 2 Humble
        run: |
          # Add ROS 2 repository
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          
          # Install ROS 2 
          sudo apt update
          sudo apt install -y ros-humble-desktop

      # Install ROS dependencies
      - name: Install ROS Dependencies
        run: |
          sudo apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            python3-vcstool

      # Initialize rosdep
      - name: Initialize rosdep
        run: |
          sudo rosdep init
          rosdep update

      # Prepare ROS environment
      - name: Prepare ROS Environment
        run: |
          # Create a script to source ROS setup
          echo '#!/bin/bash
          source /opt/ros/humble/setup.bash' > $GITHUB_WORKSPACE/ros_setup.sh
          chmod +x $GITHUB_WORKSPACE/ros_setup.sh

      # Run tests with ROS environment
      - name: Run Tests
        run: |
          $GITHUB_WORKSPACE/ros_setup.sh
          julia --project=. -e 'using Pkg; Pkg.test()'
        shell: bash

      # Optional: Upload coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
>>>>>>> d4d7d0ab4d7100c8169284283778f3267f5f96fa
