name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
        os:
          - ubuntu-22.04
        arch:
          - x64
        include:
          - os: ubuntu-22.04
            ros-distro: humble

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Julia environment
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache Julia dependencies
      - name: Cache Julia Dependencies
        uses: julia-actions/cache@v2

      # Set up ROS 2 
      - name: Set up ROS 2 ${{ matrix.ros-distro }}
        run: |
          # Add ROS 2 repository
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          
          # Install ROS 2 
          sudo apt update
          sudo apt install -y ros-${{ matrix.ros-distro }}-desktop
          
          # Set up environment
          echo "source /opt/ros/${{ matrix.ros-distro }}/setup.bash" >> $GITHUB_ENV

      # Install ROS dependencies
      - name: Install ROS Dependencies
        run: |
          sudo apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            python3-vcstool
          
          # Initialize rosdep
          sudo rosdep init
          rosdep update

      # Prepare Julia environment with ROS dependencies
      - name: Prepare Julia Environment
        run: |
          julia -e '
            using Pkg
            Pkg.add(["ROS", "PyCall"])
            Pkg.build(["ROS", "PyCall"])
          '
        shell: bash

      # Run tests
      - name: Run Tests
        run: |
          source $GITHUB_ENV
          julia --project=. -e 'using Pkg; Pkg.test()'
        shell: bash

      # Optional: Upload coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
