name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Julia environment
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache Julia dependencies
      - uses: julia-actions/cache@v2

      # Install ROS 2 Jazzy
      - name: Set up ROS 2 Jazzy
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/rosdep.key | sudo tee /etc/apt/trusted.gpg.d/ros.asc
          sudo apt update
          sudo apt install -y ros-jazzy-desktop
          source /opt/ros/jazzy/setup.bash
          echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
          source ~/.bashrc

      # Set up ROS dependencies
      - name: Install ROS dependencies
        run: |
          sudo apt install -y python3-colcon-common-extensions
          sudo apt install -y python3-pip
          pip3 install -U setuptools
          pip3 install colcon-common-extensions

      # Run tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
